#!/usr/bin/env python3
"""
finalize_fullpool.py — Regenerate the paper's retrieval macros from the
full-pool evaluation with bootstrap CIs.

Supersedes the retrieval half of finalize_scaled_results.py, which reported a
single 300-question sample. Reads:
  phase2/reports/confidence.json            (full pool, bootstrap CIs)
  phase2/reports/permutation_fullpool.json  (paired permutation tests)
Writes paper/{scaled_numbers,table1,loop_numbers,sparsity_numbers}.tex.

finalize_scaled_results.py still owns the generation (RQ2) and LIBRA-CAT macros.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
_ap = argparse.ArgumentParser()
_ap.add_argument("--tag", default="", help='e.g. "_1300" to read confidence_1300.json')
_ap.add_argument("--released-qa",
                 default="phase1/data/libra_qa_full_polished.jsonl",
                 help="the question file that ships with the benchmark; its line "
                      "count becomes \\QaReleased")
_ap.add_argument("--macro-prefix", default="",
                 help='prefix for a cross-reference macro file, e.g. "Ext", so the '
                      'conference paper can cite the large-scale replication without '
                      'hardcoding its numbers')
_ap.add_argument("--tex-dir", default="paper",
                 help="where the .tex macro files go; point a non-default --tag at its "
                      "own directory so it does not clobber the submitted paper's macros")
_args = _ap.parse_args()
TAG = _args.tag
TEX = _args.tex_dir
C = json.loads((ROOT / f"phase2/reports/confidence{TAG}.json").read_text())
P = json.loads((ROOT / f"phase2/reports/permutation_fullpool{TAG}.json").read_text())
cfg = C["configs"]


def cmd(n, v):
    return r"\newcommand{" + n + r"}{" + str(v) + "}"


def fmt_p(p):
    return r"$p<0.001$" if p < 0.001 else f"$p={p:.3f}$"


def ci(label, t):
    e = cfg[label][t]
    return f"[{e['ci95'][0]:.3f}, {e['ci95'][1]:.3f}]"


def m(label, t):
    return f"{cfg[label][t]['mean']:.3f}"


n_q = C["n_pool"]
mv = P["meta_vs_hybrid"]
lines = [f"% scaled_numbers.tex - AUTO-GENERATED by finalize_fullpool.py (full pool, n={n_q}).",
         cmd(r"\NBooks", C.get("n_books", 227)), cmd(r"\NQ", f"{n_q:,}".replace(",", "{,}")),
         cmd(r"\NCorpusChunks", f"{C.get('n_chunks', 88264):,}".replace(",", "{,}")),
         cmd(r"\OverallMeta", m("meta", "overall")), cmd(r"\OverallHybrid", m("hybrid", "overall")),
         cmd(r"\TopicalMeta", m("meta", "topical")), cmd(r"\TopicalHybrid", m("hybrid", "topical")),
         cmd(r"\TopicalDense", m("dense", "topical")),
         cmd(r"\TopicalMetaCI", ci("meta", "topical")), cmd(r"\TopicalHybridCI", ci("hybrid", "topical")),
         cmd(r"\TopicalP", fmt_p(mv["topical"]["p"])),
         cmd(r"\KnownMeta", m("meta", "known_item")), cmd(r"\KnownHybrid", m("hybrid", "known_item")),
         cmd(r"\KnownP", fmt_p(mv["known_item"]["p"])), cmd(r"\KnownN", mv["known_item"]["n"]),
         cmd(r"\BibMeta", m("meta", "bib_fact")), cmd(r"\BibHybrid", m("hybrid", "bib_fact")),
         cmd(r"\BibP", fmt_p(mv["bib_fact"]["p"])),
         cmd(r"\TopicalN", mv["topical"]["n"]),
         # size of the released question set, counted from the file that ships
         cmd(r"\QaReleased",
             f"{sum(1 for _ in open(ROOT / _args.released_qa)):,}".replace(",", "{,}")),
         cmd(r"\TopicalRelGain",
             f"{100 * (cfg['meta']['topical']['mean'] / cfg['hybrid']['topical']['mean'] - 1):.0f}")]
(ROOT / f"{TEX}/scaled_numbers.tex").write_text("\n".join(lines) + "\n")

if _args.macro_prefix:
    P = _args.macro_prefix
    xr = [f"% {P.lower()}_reference.tex - AUTO-GENERATED by finalize_fullpool.py "
          f"(tag={TAG or 'default'}, n={n_q}).",
          cmd(rf"\{P}NBooks", f"{C.get('n_books', 0):,}".replace(",", "{,}")),
          cmd(rf"\{P}NQ", f"{n_q:,}".replace(",", "{,}")),
          cmd(rf"\{P}BibMeta", m("meta", "bib_fact")),
          cmd(rf"\{P}BibHybrid", m("hybrid", "bib_fact")),
          cmd(rf"\{P}BibP", fmt_p(mv["bib_fact"]["p"])),
          cmd(rf"\{P}BibN", mv["bib_fact"]["n"]),
          cmd(rf"\{P}TopicalMeta", m("meta", "topical")),
          cmd(rf"\{P}TopicalHybrid", m("hybrid", "topical")),
          cmd(rf"\{P}TopicalP", fmt_p(mv["topical"]["p"]))]
    (ROOT / f"paper/{P.lower()}_reference.tex").write_text("\n".join(xr) + "\n")

# fusion-level ablation (meta4). Emitted only once the full-pool run has scored
# it; the paragraph in experiments_scaled.tex reads these macros.
if "meta4" in cfg:
    fus = [f"% fusion_numbers.tex - AUTO-GENERATED by finalize_fullpool.py (n={n_q}).",
           cmd(r"\FourTopical", m("meta4", "topical")),
           cmd(r"\FourOverall", m("meta4", "overall")),
           cmd(r"\FourBib", m("meta4", "bib_fact")),
           cmd(r"\FourKnown", m("meta4", "known_item"))]
    (ROOT / f"{TEX}/fusion_numbers.tex").write_text("\n".join(fus) + "\n")

rows = []
for t, lab in (("known_item", r"known\_item"), ("topical", r"\textbf{topical}"),
               ("bib_fact", r"bib\_fact")):
    cells = " & ".join(m(c, t) for c in ("dense", "bm25", "hybrid"))
    meta = m("meta", t)
    rows.append(f"{lab} & {cells} & " +
                (f"\\textbf{{{meta}}}" if t == "topical" else meta) + r" \\")
overall = " & ".join(m(c, "overall") for c in ("dense", "bm25", "hybrid"))
(ROOT / f"{TEX}/table1.tex").write_text(
    f"% table1.tex - AUTO-GENERATED by finalize_fullpool.py (full pool, n={n_q}).\n"
    "\\begin{tabular}{lcccc}\n\\toprule\nQuestion type & dense & bm25 & hybrid & "
    "\\textbf{\\method{}} \\\\\n\\midrule\n" + "\n".join(rows) +
    f"\n\\midrule\n\\textbf{{overall}} & {overall} & \\textbf{{{m('meta','overall')}}} \\\\\n"
    "\\bottomrule\n\\end{tabular}\n")

loop = [f"% loop_numbers.tex - AUTO-GENERATED by finalize_fullpool.py (full pool, n={n_q})."]
for lab, tag in (("loop_none", "None"), ("loop_llm", "Llm"), ("loop_gold", "Gold"),
                 ("loop_llm_matched", "LlmMatched")):
    loop += [cmd(rf"\Loop{tag}Topical", m(lab, "topical")),
             cmd(rf"\Loop{tag}Overall", m(lab, "overall")),
             cmd(rf"\Loop{tag}Known", m(lab, "known_item")),
             cmd(rf"\Loop{tag}Bib", m(lab, "bib_fact"))]
loop += [cmd(r"\LoopGoldCovered", C.get("n_gold_covered", 156)),
         cmd(r"\LoopNoGold", C.get("n_no_gold", 71)),
         cmd(r"\LoopNRecords", C.get("n_books", 227))]
(ROOT / f"{TEX}/loop_numbers.tex").write_text("\n".join(loop) + "\n")

ev = P["enr_vs_base"]
names = {"0.00": "Zero", "0.25": "TwentyFive", "0.50": "Fifty", "0.75": "SeventyFive", "1.00": "Hundred"}
sp = [f"% sparsity_numbers.tex - AUTO-GENERATED by finalize_fullpool.py (full pool, n={n_q})."]
for lvl, tag in names.items():
    b, e = cfg[f"sp_base{lvl}"]["topical"]["mean"], cfg[f"sp_enr{lvl}"]["topical"]["mean"]
    sp += [cmd(rf"\SpBase{tag}", f"{b:.3f}"), cmd(rf"\SpEnr{tag}", f"{e:.3f}"),
           cmd(rf"\SpGain{tag}", f"{e - b:.3f}")]
sp += [cmd(r"\SpNGold", C.get("n_gold_covered", 156)),
       cmd(r"\SpNRecords", C.get("n_books", 227)),
       cmd(r"\SpEnrHundredCI", ci("sp_enr1.00", "topical")),
       cmd(r"\SpBaseHundredCI", ci("sp_base1.00", "topical")),
       cmd(r"\SpP", fmt_p(ev["topical"]["p"])),
       cmd(r"\SpKnownP", fmt_p(ev["known_item"]["p"])),
       cmd(r"\SpEnrKnown", m("sp_enr1.00", "known_item")),
       cmd(r"\SpBaseKnown", m("sp_base1.00", "known_item"))]
(ROOT / f"{TEX}/sparsity_numbers.tex").write_text("\n".join(sp) + "\n")

# noise robustness (subject corruption), full pool
if "noise0.00" in cfg:
    ns = [f"% noise_numbers.tex - AUTO-GENERATED by finalize_fullpool.py (n={n_q})."]
    for lvl, tag in (("0.00", "Zero"), ("0.25", "TwentyFive"), ("0.50", "Fifty"),
                     ("0.75", "SeventyFive"), ("1.00", "Hundred")):
        k = f"noise{lvl}"
        ns += [cmd(rf"\Noise{tag}Topical", m(k, "topical")),
               cmd(rf"\Noise{tag}Overall", m(k, "overall")),
               cmd(rf"\Noise{tag}Known", m(k, "known_item")),
               cmd(rf"\Noise{tag}Bib", m(k, "bib_fact"))]
    (ROOT / f"{TEX}/noise_numbers.tex").write_text("\n".join(ns) + "\n")
print(f"Regenerated 4 macro files from the full pool (n={n_q}).")
